#define EE_HANDS
#define SPLIT_POINTING_ENABLE
#undef USB_VBUS_PINtt
#define SPLIT_USB_TIMEOUT 5000
#define SPLIT_USB_TIMEOUT_POLL 25
#define SERIAL_DEBUG


#define POINTING_DEVICE_COMBINED

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_PIO_USE_PIO01 cd
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define JOYSTICK_BUTTON_COUNT 16
#define JOYSTICK_AXIS_COUNT 3
#define JOYSTICK_AXIS_RESOLUTION 10

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_INVERT_Y